name: Ubuntu

on:
  push:
    branches: [ v7.x ]
  pull_request:
    branches: [ v7.x ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven and generate coverage report
      env:
        GITHUB_USERNAME: williamniemiec
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -Djava.awt.headless=true --settings settings.xml --file pom.xml jacoco:prepare-agent resources:testResources install jacoco:report
    - uses: codecov/codecov-action@v1
      with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
