name: Ubuntu

on:
  push:
    branches: [ v8.x ]
  pull_request:
    branches: [ v8.x ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn -Djava.awt.headless=true --file pom.xml jacoco:prepare-agent resources:testResources install jacoco:report
